version: '3.8'

services:
  web:
    build: .
    container_name: web_container
    restart: always
    ports:
      - "8101:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
